/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera, PerspectiveCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/xNcB9vIJZhtTQGVX/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#aeaba1']} />
      <group {...props} dispose={null}>
        <scene name="Arcade Portfolio">
          <PerspectiveCamera
            name="Movement"
            makeDefault={true}
            zoom={1.11}
            far={100000}
            near={70}
            fov={54.5}
            up={[0, 1, 0]}
            position={[1891.82, 945.68, -622.95]}
            rotation={[-2.39, 1.08, 2.45]}
            scale={1}
          />
          <group name="spotlights" position={[1071.74, 1174.25, -574.12]}>
            <spotLight
              name="Spot Light 4"
              castShadow
              intensity={7.23}
              angle={Math.PI / 6}
              penumbra={1}
              decay={0}
              distance={1768}
              shadow-mapSize-width={1024}
              shadow-mapSize-height={1024}
              shadow-camera-fov={119.99999999999999}
              shadow-camera-near={100}
              shadow-camera-far={100000}
              color="#fe0000"
              position={[-602.54, 406.98, 547.74]}
              rotation={[-0.97, -0.53, -0.71]}
              scale={1}
            />
            <spotLight
              name="Spot Light 3"
              castShadow
              intensity={7.23}
              angle={0.4}
              penumbra={1}
              decay={0}
              distance={1743}
              shadow-mapSize-width={1024}
              shadow-mapSize-height={1024}
              shadow-camera-fov={119.99999999999999}
              shadow-camera-near={100}
              shadow-camera-far={100000}
              color="#59fe5f"
              position={[133.29, -406.98, -143.62]}
              rotation={[-1.14, -0.4, -1.3]}
              scale={1}
            />
            <spotLight
              name="Spot Light 2"
              castShadow
              intensity={7.16}
              angle={0.51}
              penumbra={1}
              decay={0}
              distance={925}
              shadow-mapSize-width={1024}
              shadow-mapSize-height={1024}
              shadow-camera-fov={119.99999999999999}
              shadow-camera-near={100}
              shadow-camera-far={100000}
              color="#f8bffe"
              position={[602.54, 142.95, 29.94]}
              rotation={[-1.14, -0.4, -0.44]}
              scale={1}
            />
            <spotLight
              name="Spot Light"
              castShadow
              intensity={10}
              angle={Math.PI / 6}
              penumbra={1}
              decay={0.2}
              distance={1743}
              shadow-mapSize-width={4096}
              shadow-mapSize-height={4096}
              shadow-camera-fov={119.99999999999999}
              shadow-camera-near={100}
              shadow-camera-far={100000}
              color="#fef7e2"
              position={[-322.19, 30.01, -547.74]}
              rotation={[-0.91, -0.51, -0.36]}
              scale={1}
            />
          </group>
          <group name="arcade room" position={[203.51, 739.34, 128.37]}>
            <mesh
              name="left wall"
              geometry={nodes['left wall'].geometry}
              material={materials['left wall Material']}
              castShadow
              receiveShadow
              position={[1.51, 0, 1138.63]}
              rotation={[0, 0, -Math.PI]}
              scale={[1.23, 0.82, 1.23]}
            />
            <mesh
              name="right wall"
              geometry={nodes['right wall'].geometry}
              material={materials['right wall Material']}
              castShadow
              receiveShadow
              position={[-1229.72, 0, -1.45]}
              rotation={[-Math.PI, Math.PI / 2, 0]}
              scale={[1.23, 0.82, 1.23]}
            />
            <mesh
              name="floor"
              geometry={nodes.floor.geometry}
              material={materials['floor Material']}
              castShadow
              receiveShadow
              position={[-1.56, -819.64, -1.44]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1.23}
            />
          </group>
          <group name="KIEFER Arcade Machine" position={[337.69, 350.58, 5.99]} rotation={[0, 0.68, 0]}>
            <group name="Token Retrieve" position={[102.48, -233.29, 20.18]}>
              <group name="Token Retrieve 2" position={[0, 0, -46.28]}>
                <mesh
                  name="Rectangle"
                  geometry={nodes.Rectangle.geometry}
                  material={materials['Rectangle Material']}
                  castShadow
                  receiveShadow
                  position={[1.09, 0.71, 0]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1, 1.07, 1]}
                />
                <mesh
                  name="Boolean"
                  geometry={nodes.Boolean.geometry}
                  material={nodes.Boolean.material}
                  castShadow
                  receiveShadow
                />
              </group>
              <mesh
                name="Rectangle1"
                geometry={nodes.Rectangle1.geometry}
                material={materials['Rectangle1 Material']}
                castShadow
                receiveShadow
                position={[1.09, 0.71, 0]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[1, 1.07, 1]}
              />
              <mesh
                name="Boolean1"
                geometry={nodes.Boolean1.geometry}
                material={nodes.Boolean1.material}
                castShadow
                receiveShadow
              />
            </group>
            <mesh
              name="Quarter only "
              geometry={nodes['Quarter only '].geometry}
              material={materials['Quarter only  Material']}
              castShadow
              receiveShadow
              position={[100.76, -211.22, 1.65]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.61}
            />
            <group name="Key hole" position={[101.99, -218.21, -39.85]} scale={0.86}>
              <group name="Key hole 2" position={[0, -68.62, 0]}>
                <mesh
                  name="Boolean2"
                  geometry={nodes.Boolean2.geometry}
                  material={nodes.Boolean2.material}
                  castShadow
                  receiveShadow
                  position={[1.28, 0, 0]}
                />
                <mesh
                  name="Ellipse"
                  geometry={nodes.Ellipse.geometry}
                  material={materials['Ellipse Material']}
                  castShadow
                  receiveShadow
                  position={[-2.76, 0, 0]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1, 1, 0.63]}
                />
              </group>
              <mesh
                name="Boolean3"
                geometry={nodes.Boolean3.geometry}
                material={nodes.Boolean3.material}
                castShadow
                receiveShadow
                position={[1.28, 0, 0]}
              />
              <mesh
                name="Ellipse1"
                geometry={nodes.Ellipse1.geometry}
                material={materials['Ellipse1 Material']}
                castShadow
                receiveShadow
                position={[-2.76, 0, 0]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[1, 1, 0.63]}
              />
            </group>
            <group name="Token Insert" position={[104.46, -178.61, -25.87]} scale={0.69}>
              <group name="Token Insert 2" position={[0, 0, 65.76]}>
                <mesh
                  name="Boolean4"
                  geometry={nodes.Boolean4.geometry}
                  material={nodes.Boolean4.material}
                  castShadow
                  receiveShadow
                  position={[-0.36, 0, 0]}
                />
                <mesh
                  name="Rectangle2"
                  geometry={nodes.Rectangle2.geometry}
                  material={materials['Rectangle2 Material']}
                  castShadow
                  receiveShadow
                  position={[-1.79, -1.38, -4.6]}
                  rotation={[-Math.PI / 2, 1.41, Math.PI / 2]}
                  scale={1}
                />
              </group>
              <mesh
                name="Boolean5"
                geometry={nodes.Boolean5.geometry}
                material={nodes.Boolean5.material}
                castShadow
                receiveShadow
                position={[-0.36, 0, 0]}
              />
              <mesh
                name="Rectangle3"
                geometry={nodes.Rectangle3.geometry}
                material={materials['Rectangle3 Material']}
                castShadow
                receiveShadow
                position={[-1.79, -1.38, -4.6]}
                rotation={[-Math.PI / 2, 1.41, Math.PI / 2]}
                scale={1}
              />
            </group>
            <mesh
              name="KIEFER"
              geometry={nodes.KIEFER.geometry}
              material={materials['KIEFER Material']}
              castShadow
              receiveShadow
              position={[60.4, 274.02, -3.96]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1.48}
            />
            <group name="Red Buttons" position={[82.83, -19.98, 24.84]}>
              <group name="red button 3" position={[0, 0, -28.64]} rotation={[0, 0, 0.02]} scale={0.94}>
                <mesh
                  name="Ellipse 2"
                  geometry={nodes['Ellipse 2'].geometry}
                  material={materials['Ellipse 2 Material']}
                  castShadow
                  receiveShadow
                  position={[0.34, -0.2, 0]}
                  rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                  scale={[1.07, 1.05, 1.28]}
                />
                <mesh
                  name="Ellipse2"
                  geometry={nodes.Ellipse2.geometry}
                  material={materials['Ellipse2 Material']}
                  castShadow
                  receiveShadow
                  position={[-1.04, -3.97, 0]}
                  rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                  scale={[1.26, 1.23, 1.51]}
                />
              </group>
              <group name="red button 2" position={[0, 0, 0.35]} rotation={[0, 0, 0.02]} scale={0.94}>
                <mesh
                  name="Ellipse 21"
                  geometry={nodes['Ellipse 21'].geometry}
                  material={materials['Ellipse 21 Material']}
                  castShadow
                  receiveShadow
                  position={[0.34, -0.2, 0]}
                  rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                  scale={[1.07, 1.05, 1.28]}
                />
                <mesh
                  name="Ellipse3"
                  geometry={nodes.Ellipse3.geometry}
                  material={materials['Ellipse3 Material']}
                  castShadow
                  receiveShadow
                  position={[-1.04, -3.97, 0]}
                  rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                  scale={[1.26, 1.23, 1.51]}
                />
              </group>
              <group name="red button 1" position={[0, 0, 28.64]} rotation={[0, 0, 0.02]} scale={0.94}>
                <mesh
                  name="Ellipse 22"
                  geometry={nodes['Ellipse 22'].geometry}
                  material={materials['Ellipse 22 Material']}
                  castShadow
                  receiveShadow
                  position={[0.34, -0.2, 0]}
                  rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                  scale={[1.07, 1.05, 1.28]}
                />
                <mesh
                  name="Ellipse4"
                  geometry={nodes.Ellipse4.geometry}
                  material={materials['Ellipse4 Material']}
                  castShadow
                  receiveShadow
                  position={[-1.04, -3.97, 0]}
                  rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                  scale={[1.26, 1.23, 1.51]}
                />
              </group>
            </group>
            <group name="Yellow Button" position={[84.7, -20.49, -105.4]} rotation={[0, 0, 0.01]} scale={1.71}>
              <mesh
                name="Ellipse 23"
                geometry={nodes['Ellipse 23'].geometry}
                material={materials['Ellipse 23 Material']}
                castShadow
                receiveShadow
                position={[0.34, -0.2, 0]}
                rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                scale={[0.95, 0.93, 1.14]}
              />
              <mesh
                name="Ellipse5"
                geometry={nodes.Ellipse5.geometry}
                material={materials['Ellipse5 Material']}
                castShadow
                receiveShadow
                position={[-1.04, -3.97, 0]}
                rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                scale={[1.26, 1.23, 1.51]}
              />
            </group>
            <group name="Blue Button" position={[110.03, -30.16, -54.73]} rotation={[0, 0, 0.01]} scale={1.71}>
              <mesh
                name="Ellipse 1"
                geometry={nodes['Ellipse 1'].geometry}
                material={materials['Ellipse 1 Material']}
                castShadow
                receiveShadow
                position={[0.34, -0.2, 0]}
                rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                scale={[0.95, 0.93, 1.14]}
              />
              <mesh
                name="Ellipse6"
                geometry={nodes.Ellipse6.geometry}
                material={materials['Ellipse6 Material']}
                castShadow
                receiveShadow
                position={[-1.04, -3.97, 0]}
                rotation={[-Math.PI / 2, 0.35, -Math.PI / 2]}
                scale={[1.26, 1.23, 1.51]}
              />
            </group>
            <group name="Joystick" position={[117.46, 0.46, 105.67]} rotation={[0, 0, -0.35]} scale={0.19}>
              <mesh
                name="Boolean6"
                geometry={nodes.Boolean6.geometry}
                material={nodes.Boolean6.material}
                castShadow
                receiveShadow
                position={[0, -161.35, 0]}
              />
              <group name="stick" position={[0.13, -184.93, -0.37]}>
                <mesh
                  name="Sphere"
                  geometry={nodes.Sphere.geometry}
                  material={materials['Sphere Material']}
                  castShadow
                  receiveShadow
                  position={[-23.61, -183.97, -0.67]}
                  rotation={[-1.45, 1.57, 1.46]}
                  scale={5.31}
                />
                <mesh
                  name="Cylinder"
                  geometry={nodes.Cylinder.geometry}
                  material={materials['Cylinder Material']}
                  castShadow
                  receiveShadow
                  position={[-21.1, -38.35, 0.26]}
                  rotation={[0, 0, 0]}
                  scale={[1, 2.14, 1]}
                />
                <mesh
                  name="Sphere1"
                  geometry={nodes.Sphere1.geometry}
                  material={materials['Sphere1 Material']}
                  castShadow
                  receiveShadow
                  position={[-21.21, 81.29, 0]}
                />
              </group>
            </group>
            <mesh
              name="Screen Placeholder"
              geometry={nodes['Screen Placeholder'].geometry}
              material={materials['Screen Placeholder Material']}
              castShadow
              receiveShadow
              position={[38.87, 85.38, -0.13]}
              rotation={[Math.PI / 2, -1.3, -Math.PI / 2]}
              scale={[-1, 0.87, 0.79]}
            />
            <mesh
              name="screen border"
              geometry={nodes['screen border'].geometry}
              material={materials['screen border Material']}
              castShadow
              receiveShadow
              position={[33.01, 81.98, 1.85]}
              rotation={[Math.PI / 2, -1.3, -Math.PI / 2]}
              scale={[-1.21, 1.07, 2.63]}
            />
            <mesh
              name="screen border1"
              geometry={nodes['screen border1'].geometry}
              material={materials['screen border1 Material']}
              castShadow
              receiveShadow
              position={[30.22, 81.71, 1.69]}
              rotation={[Math.PI / 2, -1.3, -Math.PI / 2]}
              scale={[-1.18, 1.02, 2.63]}
            />
            <mesh
              name="left side"
              geometry={nodes['left side'].geometry}
              material={materials.Outlines}
              castShadow
              receiveShadow
              position={[-139.87, 249.85, -147.54]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={1}
            />
            <mesh
              name="right side"
              geometry={nodes['right side'].geometry}
              material={materials.Outlines}
              castShadow
              receiveShadow
              position={[-140.87, 249.85, 151.69]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={1}
            />
            <mesh
              name="Rectangle4"
              geometry={nodes.Rectangle4.geometry}
              material={materials['Rectangle4 Material']}
              castShadow
              receiveShadow
              position={[63.15, 271, -4]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.88}
            />
            <mesh
              name="cabinet body"
              geometry={nodes['cabinet body'].geometry}
              material={nodes['cabinet body'].material}
              castShadow
              receiveShadow
              position={[0.15, -10.69, -8.66]}
            />
            <group name="Bottom Panel" position={[87.73, -229.15, -5.35]} scale={[1, 1.2, 1.08]}>
              <group name="Border" position={[0, 0, 0]}>
                <mesh
                  name="Rectangle 4"
                  geometry={nodes['Rectangle 4'].geometry}
                  material={materials['Rectangle 4 Material']}
                  castShadow
                  receiveShadow
                  position={[-7.34, 25.28, -0.37]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1.14, 1.06, 1.1]}
                />
                <mesh
                  name="Rectangle 3"
                  geometry={nodes['Rectangle 3'].geometry}
                  material={materials['Rectangle 3 Material']}
                  castShadow
                  receiveShadow
                  position={[-7.71, -44.92, -0.37]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1.14, 0.87, 1.1]}
                />
                <mesh
                  name="Rectangle 31"
                  geometry={nodes['Rectangle 31'].geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[-5.93, 0, 0]}
                  rotation={[-Math.PI, 1.53, -Math.PI]}
                  scale={[0.8, 0.75, 0.96]}
                />
              </group>
            </group>
          </group>
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={-2.67} color="#fefbee" />
        </scene>
      </group>
    </>
  )
}
